DROP TABLE Comments;
DROP TABLE Posts;
DROP TABLE Accounts;

CREATE TABLE Accounts (
    username VARCHAR(20) PRIMARY KEY,
    /*UUID will be used for Token-based user authentication from zyBooks section 10.16.
      Uses UUID V4*/
    uuid VARCHAR(36) NOT NULL,
    password TEXT NOT NULL,
    creation_date DATETIME NOT NULL,
    /* Will be a value from 1-9, when creating an account
    You'll be able to pick a profile picture from 9 preset options.
    If value is outside of the range, or is NULL, default pfp will be used */
    pfp_option INTEGER,
    admin BOOLEAN NOT NULL
);

CREATE TABLE Posts (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    origin_date DATETIME NOT NULL,
    /* edit_date can be null if the post has not been edited, and
    it is implicit that a post has been edited if it is not null */
    edit_date DATETIME,
    deleted BOOLEAN NOT NULL,
    user_posted VARCHAR(20) NOT NULL,
    FOREIGN KEY(user_posted) REFERENCES Accounts(username)
);

CREATE TABLE Comments (
    comment_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    post_id INTEGER NOT NULL,
    comment_content TEXT NOT NULL,
    commented_date DATETIME NOT NULL,
    comment_deleted BOOLEAN NOT NULL,
    user_commented VARCHAR(20) NOT NULL,
    FOREIGN KEY(post_id) REFERENCES Posts(id),
    FOREIGN KEY(user_commented) REFERENCES Accounts(username)
);

/*Accounts generated by ChatGTP except for admin_account, stick_lover3000, Walter White, and squirrel_hunter.
  Prompt: Generate accounts for a dog blog website for the following format <username, uuid, password, creation_date, pfp_option, admin>*/
INSERT INTO Accounts (username, uuid, password, creation_date, pfp_option, admin) VALUES
/*Password: password123*/
('admin_account','3c08494b-7fcd-433b-a7db-49e058ae89bc','$2b$10$GJrjO5HaZx6hkkQONFyiteRPpSAoiJxry7GZdaqyFq5bHpWxvcmga','2025-5-02 07:12:00',NULL,TRUE),
/*Password: ILoveSticks*/
('stick_lover3000','59631293-ad43-4de8-9eb8-2bbaf450bbda','$2b$10$OLPZc2p20gxNDJABjFP.5ui04jKvzU4GeUxzQsdm3FQDSa8AG68C6','2024-1-09 11:12:00',1,FALSE),
/*Password: cargopants11*/
('squirrel_hunter','6f01fc3b-7220-4ff2-ae3a-d1f0727a58a4','$2b$10$eJud8jIkkB4o9QB3PTWZOe5.LwSRTm0SBanyP54snMZNVPfAeoVE.','2025-8-05 14:01:00',2,FALSE),
/*Password: HugeBork99*/
('big_dog_energy','a923b41d-8f02-4f4e-a268-b97e9ef127cd','$2b$10$BRsPmEr0V3uKzY9lIPsG8eq7q7eXQ.PmBWKbprKC2VZRvCmQ8IXea','2025-02-19 09:25:00',3,FALSE),
/*Password: BreakingBad42*/
('Walter White','3c0276d2-8330-4145-83cf-3e3ad957bd71','$2b$10$Q/XXVF18swCe8BkFXkhdhOegLNEJLb3siT4yJidlB5YRdkz6016hy','2008-1-20 16:30:00',4,FALSE),
/*Password: Treats4Life*/
('treat_connoisseur','be21ad8c-2c42-44a7-9cc3-a0cd2fdc23d0','$2b$10$4KIHuJk60JpcOnSBhCRCAO3aQd7yvjYrpYRGY.oHfienzKLGYxrS2','2025-05-11 14:58:00',5,FALSE),
/*Password: FastAsHeck*/
('zoomie_master','c98e5c48-67e4-4bc6-9c81-3f7f0d3fbbb5','$2b$10$Ntw3eRkAwwrzl3TX4/ReY.NF6SkdPwZ1b0TE.kgmRFPswnYl52sIG','2025-06-07 18:22:00',6,FALSE),
/*Password: ArchiveBone*/
('bone_archivist','d6ff4032-4178-4bd0-84cd-4df6186efd42','$2b$10$5L/RV.1.Y5m1MFOHdO7sy.PF2W0XXVt78JPA32NtrMFzGt.7wTSuy','2023-11-23 10:44:00',7,FALSE),
/*Password: SleepyTime*/
('nap_professional','e52a1f91-91c9-4c0b-9af9-9c52d88135f8','$2b$10$WicyDGV6r.SUT3PZNuBedeTGzo7YqaBPhYmmJvpmUAw9CL3xvzfiS','2024-03-15 16:05:00',8,FALSE),
/*Password: HowlMaster77*/
('howl_expert','f73ca9d4-6a8c-42c2-b5ee-cc93e76e9182','$2b$10$LFeV0sX8f0EU7U1gHY7deOgQNZ9E3.smQX.rr2cHwUzhrqFWE7ram','2025-04-02 13:40:00',9,FALSE);

/*This posts data generated by ChatGTP except for post 4.
  Prompt: Generate posts for a dog blog with the following format <id, title, content, origin_date, edit_date, deleted, user_posted>*/
INSERT INTO Posts (id, title, content, origin_date, edit_date, deleted, user_posted) VALUES
(0,'Morning Zoomies Report','Ran in circles for 12 minutes. No regrets. 10/10 morning.','2025-10-01 07:12:00',NULL,FALSE,'zoomie_master'),
(1,'Suspicious Squirrel Activity','Saw a squirrel outside. He made eye contact. Something is brewing.','2025-10-01 09:45:00',NULL,FALSE,'squirrel_hunter'),
(2,'The Mailman Approaches','Mailman spotted. Sounding the alarm. Bark protocols activated.','2025-10-01 11:02:00',NULL,FALSE,'big_dog_energy'),
(3,'Lunch Bowl Review','Lunch was kibble again. Good crunch. Would eat more if allowed.','2025-10-01 12:30:00',NULL,FALSE,'treat_connoisseur'),
(4,'Gus is onto me','Fring wants me gone. Jesse has to do something about Gale or we are both done for.','2025-10-01 14:15:00',NULL,FALSE,'Walter White'),
(5,'Favorite Stick Rediscovered','Found my lost stick under the couch. A reunion for the ages.','2025-10-01 15:47:00',NULL,FALSE,'stick_lover3000'),
(6,'Spotted a Big Dog','Big dog at park. Very big. Like, unnecessarily big. Respect.','2025-10-01 16:10:00',NULL,FALSE,'big_dog_energy'),
(7,'Belly Rub Success','Executed perfect puppy eyes. Earned 4 minutes of belly rubs.','2025-10-01 17:25:00',NULL,FALSE,'howl_expert'),
(8,'Illegal Vacuum Activity','Vacuum turned on again. Humans never learn. I barked bravely.','2025-10-01 18:40:00',NULL,FALSE,'zoomie_master'),
(9,'Dinner Excitement','Dinner time!!!!! Ran to bowl at mach speed.','2025-10-01 19:01:00',NULL,FALSE,'treat_connoisseur'),
(10,'Night Patrol','Neighborhood secure. No cats detected. For now.','2025-10-01 20:33:00',NULL,FALSE,'squirrel_hunter'),
(11,'New Toy Acquired','Human brought home squeaky bone. Squeaked it 87 times so far.','2025-10-02 08:10:00',NULL,FALSE,'bone_archivist'),
(12,'Mystery Smell Investigation','Found strange smell by the trash can. Smelled it for 4 straight minutes.','2025-10-02 10:55:00',NULL,FALSE,'big_dog_energy'),
(13,'Couch Jump Attempt','Attempted to jump onto couch. Missed. Pretended it was intentional.','2025-10-02 12:14:00',NULL,FALSE,'stick_lover3000'),
(14,'Sunbeam Nap','Found warm sunbeam on floor. Took elite-level nap.','2025-10-02 14:50:00',NULL,FALSE,'nap_professional'),
(15,'Unauthorized Bath','Received bath without consent. Will be filing a formal complaint.','2025-10-01 14:15:00',NULL,FALSE,'howl_expert');

